import 'package:isar/isar.dart';

// NOTE: This file will be generated by running:
// flutter pub run build_runner build --delete-conflicting-outputs
// The error below is expected until the generated file exists.
part 'isar_models.g.dart';

@collection
class GameStateSnapshot {
  Id id = Isar.autoIncrement;

  @Index(unique: true)
  late String roomCode;

  late int stateVersion;

  String? currentTurnPlayerId;

  late int direction;

  late String activeColor;

  late int pendingDrawCount;

  late int drawPileCount;

  @Index()
  late DateTime lastUpdated;

  String? winnerPlayerId;

  DateTime? winnerTimestamp;

  String? lastPlayedCardAnimationId;

  late String roomStatus; // 'lobby', 'playing', or 'finished'
}

@collection
class DiscardPileCard {
  Id id = Isar.autoIncrement;

  @Index()
  late String roomCode;

  late int cardIndex;

  late String color;

  late String type;

  int? number;

  @Index()
  late DateTime addedAt;
}

@collection
class PlayerSnapshot {
  Id id = Isar.autoIncrement;

  @Index()
  late String roomCode;

  @Index()
  late String playerId;

  late String name;

  late bool isHost;

  late bool isSpectator;

  int? seatNumber;

  late int cardCount;

  @Index()
  late DateTime lastUpdated;
}

@collection
class PlayerHand {
  Id id = Isar.autoIncrement;

  @Index(unique: true, replace: true)
  late String playerId;

  @Index()
  late String roomCode;

  late List<String> cardData;

  @Index()
  late DateTime lastUpdated;
}

@collection
class GameEvent {
  Id id = Isar.autoIncrement;

  @Index(unique: true, replace: true)
  late String eventId;

  @Index()
  late String roomCode;

  late int stateVersion;

  late String eventType;

  String? playerId;

  String? payload;

  @Index()
  late DateTime timestamp;

  late bool isPending;

  late bool isApplied;
}

@collection
class SyncMetadata {
  Id id = Isar.autoIncrement;

  @Index(unique: true, replace: true)
  late String roomCode;

  late int lastAppliedStateVersion;

  String? lastProcessedEventId;

  @Index()
  late DateTime lastSyncAt;

  late bool needsFullSync;
}

/// Tracks animation/event IDs already played so they never replay (card fly, UNO, wild, etc.).
@collection
class ConsumedAnimationId {
  Id id = Isar.autoIncrement;

  @Index(unique: true, replace: true)
  late String key;

  @Index()
  late String roomCode;
}
